//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliason.TextEditor {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eliason.TextEditor.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the text file &apos;{0}&apos;..
        /// </summary>
        internal static string FileXCouldNotLoad {
            get {
                return ResourceManager.GetString("FileXCouldNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string FileXDoesNotExist {
            get {
                return ResourceManager.GetString("FileXDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &amp; Replace.
        /// </summary>
        internal static string FindReplace_Title {
            get {
                return ResourceManager.GetString("FindReplace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application must be restarted for the new languages to be found. Do you want to restart now?.
        /// </summary>
        internal static string Languages_Download_RestartRequired {
            get {
                return ResourceManager.GetString("Languages_Download_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string Native_ItemSeparator {
            get {
                return ResourceManager.GetString("Native_ItemSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add a word with no content..
        /// </summary>
        internal static string Spellchecking_CannotAddEmptyWord {
            get {
                return ResourceManager.GetString("Spellchecking_CannotAddEmptyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellcheck complete. Has arrived at the end of the text..
        /// </summary>
        internal static string Spellchecking_EndOfText_Success {
            get {
                return ResourceManager.GetString("Spellchecking_EndOfText_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; directory does not exist. You have no lexicon/dictionary to spellcheck from..
        /// </summary>
        internal static string Spellchecking_LexiconResourcesDoesNotExist {
            get {
                return ResourceManager.GetString("Spellchecking_LexiconResourcesDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no installed lexicons to spellcheck from for the language &apos;{0}&apos;. Would you like to download some now?.
        /// </summary>
        internal static string Spellchecking_LexiconsAreNotInstalled_AskDownload {
            get {
                return ResourceManager.GetString("Spellchecking_LexiconsAreNotInstalled_AskDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no text in the text control to spellcheck..
        /// </summary>
        internal static string Spellchecking_TextControlIsEmpty {
            get {
                return ResourceManager.GetString("Spellchecking_TextControlIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellchecking.
        /// </summary>
        internal static string Spellchecking_Title {
            get {
                return ResourceManager.GetString("Spellchecking_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no handler for the text templates for dynamic template tokens. This should never happen..
        /// </summary>
        internal static string Text_Template_DynamicTokenNotFound {
            get {
                return ResourceManager.GetString("Text_Template_DynamicTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple auto-saves for the text file &apos;{0}&apos;. Select an auto-saved file (Enter), or cancel (Esc)..
        /// </summary>
        internal static string TextControl_AutoSave_MultipleOpenOptions {
            get {
                return ResourceManager.GetString("TextControl_AutoSave_MultipleOpenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available auto-save files.
        /// </summary>
        internal static string TextControl_AutoSave_MultipleOpenOptions_Title {
            get {
                return ResourceManager.GetString("TextControl_AutoSave_MultipleOpenOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are trying to open was last changed {0}, but there is an autosaved file in your temporary folder last changed {1}. Would you like to open this autosaved file instead?.
        /// </summary>
        internal static string TextControl_AutoSave_OneOpenOption_Ask {
            get {
                return ResourceManager.GetString("TextControl_AutoSave_OneOpenOption_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that the current filepath is that to the temporary. Find your original file and overwrite it, if there is nothing wrong with this temporary one..
        /// </summary>
        internal static string TextControl_AutoSave_OpenInformation {
            get {
                return ResourceManager.GetString("TextControl_AutoSave_OpenInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are changes pending for the script file &apos;{0}&apos;. Do you want to save it before closing?.
        /// </summary>
        internal static string TextControl_Close_SaveDiscardCancel {
            get {
                return ResourceManager.GetString("TextControl_Close_SaveDiscardCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This new script file has never been saved and has changes pending. Do you want to save it before closing?.
        /// </summary>
        internal static string TextControl_Close_SaveDiscardCancel_New {
            get {
                return ResourceManager.GetString("TextControl_Close_SaveDiscardCancel_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the autosave file, which means you have probably inputted a wrong autosave location, or your account does not have access to your temporary folder; you are then forced to manually write another location in the preferences..
        /// </summary>
        internal static string TextControl_CouldNotAutoSave {
            get {
                return ResourceManager.GetString("TextControl_CouldNotAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy text to the clipboard. The stated reason was: &apos;{0}&apos;..
        /// </summary>
        internal static string TextControl_CouldNotCopyToClipboardBecause {
            get {
                return ResourceManager.GetString("TextControl_CouldNotCopyToClipboardBecause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy text to the clipboard. The stated reason was: &apos;{0}&apos;. This was because there is already another application actively using the clipboad. The guess is that that application is &apos;{1}&apos;. Please try again later..
        /// </summary>
        internal static string TextControl_CouldNotCopyToClipboardBecauseOf {
            get {
                return ResourceManager.GetString("TextControl_CouldNotCopyToClipboardBecauseOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are changes pending for the file &apos;{0}&apos;, do you want to save it before opening a new file?.
        /// </summary>
        internal static string TextControl_Open_ChangesPending_Save_Ask {
            get {
                return ResourceManager.GetString("TextControl_Open_ChangesPending_Save_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text file &apos;{0}&apos; that you are trying to save is a singlebyte file, but the text you are trying to save has multibyte characters. Do you want to convert the file to Unicode (UTF-8)?.
        /// </summary>
        internal static string TextControl_Save_SinglebyteToMultibyte_Ask {
            get {
                return ResourceManager.GetString("TextControl_Save_SinglebyteToMultibyte_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds and colors the words that are set to be found..
        /// </summary>
        internal static string TextControl_Style_Highlight_Description {
            get {
                return ResourceManager.GetString("TextControl_Style_Highlight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighting.
        /// </summary>
        internal static string TextControl_Style_Highlight_Name {
            get {
                return ResourceManager.GetString("TextControl_Style_Highlight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert custom notes into the text that are only saved in Scanlationshop and not in the actual text..
        /// </summary>
        internal static string TextControl_Style_Note_Description {
            get {
                return ResourceManager.GetString("TextControl_Style_Note_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string TextControl_Style_Note_Name {
            get {
                return ResourceManager.GetString("TextControl_Style_Note_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red (by default) underline for spellchecking..
        /// </summary>
        internal static string TextControl_Style_Spellcheck_Description {
            get {
                return ResourceManager.GetString("TextControl_Style_Spellcheck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds and colors any URLs that are in the text..
        /// </summary>
        internal static string TextControl_Style_URL_Description {
            get {
                return ResourceManager.GetString("TextControl_Style_URL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string TextControl_Style_URL_Name {
            get {
                return ResourceManager.GetString("TextControl_Style_URL_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file extension for a template file must be .txt.
        /// </summary>
        internal static string TextControl_Template_FileExtensionMustBeTxt {
            get {
                return ResourceManager.GetString("TextControl_Template_FileExtensionMustBeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string TextControl_TextTemplates_Title {
            get {
                return ResourceManager.GetString("TextControl_TextTemplates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file must be saved to be able to execute a template.
        /// </summary>
        internal static string TextControl_TextTemples_TextFileMustBeSaved {
            get {
                return ResourceManager.GetString("TextControl_TextTemples_TextFileMustBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextControl_Title {
            get {
                return ResourceManager.GetString("TextControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added &apos;{0}&apos;.
        /// </summary>
        internal static string TextControl_UndoRedo_Added {
            get {
                return ResourceManager.GetString("TextControl_UndoRedo_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added &apos;{0}...&apos;.
        /// </summary>
        internal static string TextControl_UndoRedo_Added_Long {
            get {
                return ResourceManager.GetString("TextControl_UndoRedo_Added_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed &apos;{0}&apos;.
        /// </summary>
        internal static string TextControl_UndoRedo_Removed {
            get {
                return ResourceManager.GetString("TextControl_UndoRedo_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed &apos;{0}...&apos;.
        /// </summary>
        internal static string TextControl_UndoRedo_Removed_Long {
            get {
                return ResourceManager.GetString("TextControl_UndoRedo_Removed_Long", resourceCulture);
            }
        }
    }
}
